/*  Sean M.
    May 15th, 2023
    The Actual Quiz Code, this is going to suck to fix
 */

import classclass.Test;
import classclass.Question;
import java.util.Scanner;
import java.io.InputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author semel9291
 */
public class SDLC_TrueQuiz extends javax.swing.JFrame {

    private static ArrayList<String> TestQ = new ArrayList();
    private static ArrayList<Question> questions = new ArrayList();
    private static Test test = new Test(questions);

    /**
     * Creates new form SDLC_TrueQuiz
     */
    public SDLC_TrueQuiz() {
        initComponents();
        fillData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MultipleChoice = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblQNum = new javax.swing.JLabel();
        lblQText = new javax.swing.JLabel();
        btnQ1 = new javax.swing.JRadioButton();
        btnQ2 = new javax.swing.JRadioButton();
        btnQ3 = new javax.swing.JRadioButton();
        btnQ4 = new javax.swing.JRadioButton();
        btnProceed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Quiz Begin");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblQNum.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblQNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQNum.setText("Question #X");

        lblQText.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblQText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQText.setText("Why do I look this fire all the time, hot damn?");

        MultipleChoice.add(btnQ1);
        btnQ1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        btnQ1.setText("Cause I'm too hot");
        btnQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ1ActionPerformed(evt);
            }
        });

        MultipleChoice.add(btnQ2);
        btnQ2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        btnQ2.setText("Hot damn");

        MultipleChoice.add(btnQ3);
        btnQ3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        btnQ3.setText("call the police");

        MultipleChoice.add(btnQ4);
        btnQ4.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        btnQ4.setText("or the fireman");

        btnProceed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnProceed.setText("funky town ig");
        btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblQNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQ1)
                    .addComponent(btnQ3))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQ4)
                    .addComponent(btnQ2))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(btnProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblQNum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQ2)
                    .addComponent(btnQ1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQ3)
                    .addComponent(btnQ4))
                .addGap(18, 18, 18)
                .addComponent(btnProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProceedActionPerformed

    private void btnQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQ1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SDLC_TrueQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SDLC_TrueQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SDLC_TrueQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SDLC_TrueQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SDLC_TrueQuiz().setVisible(true);
                fillData();
            }
        });
    }

    public void nextQuestion() {

    }

    /**
     * public void fillData() { File f = new
     * File("src/dataFiles/TestQuestions.txt"); try { Scanner s = new
     * Scanner(f); while(s.hasNextLine()){ //Suck my cock n balls ig? }
     *
     * } catch (FileNotFoundException e) { System.out.println("ERROR: " + e); }
     *
     * }
     * *
     */
    public static void fillData() {
        Question q = new Question();
        ArrayList<String> diffAns = new ArrayList();
        int size;
        int i = 0;

        try {
            InputStream in = SDLC_TrueQuiz.class.getResourceAsStream("TestQuestions.txt");
            Scanner s = new Scanner(in);
            size = Integer.valueOf(s.nextLine());  
            while ( s.hasNextLine() ) {
                // Fill a new question object with the text of the question
                q.setText(s.nextLine());
                // Adding the different answers
                diffAns.add(i, s.nextLine());
                diffAns.add(i, s.nextLine());
                diffAns.add(i, s.nextLine());
                diffAns.add(i, s.nextLine());
                // Adding different answers ArrayList to question object
                q.setDiffAns(diffAns);
                // Marking the correct answer as an integer
                q.setCorrectAns(Integer.valueOf(s.nextLine()));
                // Add question object to arrayList
                questions.add(i, q);
                i++;
            }
            System.out.println(questions);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error reading file! ");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup MultipleChoice;
    private javax.swing.JButton btnProceed;
    private javax.swing.JRadioButton btnQ1;
    private javax.swing.JRadioButton btnQ2;
    private javax.swing.JRadioButton btnQ3;
    private javax.swing.JRadioButton btnQ4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblQNum;
    private javax.swing.JLabel lblQText;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
